import Footer from '@/components/Footer'
import './globals.css'
import Navbar from '@/components/Navbar'
import Provider from '@/components/Provider'

export const metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='overflow-x-hidden bg-gray-100'>
        <Provider>
          <main className='w-full'>
            <Navbar />
              {children}
            <Footer />
          </main>       
        </Provider>
      </body>
    </html>
  )
}
